module.exports = {
  nietzsche2: ["nietzsche", "gai", "savoir", "notre", "nit", "plus", "grand", "cent", "nement", "savoir", "que",
    "dieu", "est", "mort", "que", "croyance", "dieu", "chr", "tien", "est", "tomb", "discr", "dit", "commence",
    "maintenant", "tendre", "son", "ombre", "sur", "europe", "aux", "quelques", "rares", "tout", "moins", "dou",
    "une", "suspicion", "assez", "trante", "regard", "assez", "subtil", "pour", "spectacle", "semble", "effet",
    "que", "quelque", "soleil", "vienne", "cliner", "que", "quelque", "vieille", "profonde", "confiance", "soit",
    "retourn", "doute", "ceux", "notre", "vieux", "monde", "doit", "para", "tre", "jour", "jour", "plus", "pusculaire",
    "plus", "fiant", "plus", "tranger", "plus", "vieux", "mais", "sous", "rapport", "essentiel", "peut", "dire",
    "nement", "soi", "est", "beaucoup", "trop", "consid", "rable", "trop", "lointain", "trop", "del", "facult",
    "conceptuelle", "grand", "nombre", "pour", "que", "puisse", "tendre", "que", "nouvelle", "soit", "parvenue",
    "bien", "moins", "encore", "que", "aucuns", "rendent", "compte", "qui", "est", "ellement", "pass", "comme",
    "tout", "qui", "doit", "sormais", "effondrer", "une", "fois", "ruin", "cette", "croyance", "pour", "avoir",
    "fond", "sur", "elle", "pour", "ainsi", "dire", "enchev", "elle", "par", "exemple", "notre", "morale", "europ",
    "enne", "dans", "totalit", "cette", "longue", "conde", "succession", "ruptures", "destructions", "clins",
    "bouleversements", "faut", "voir", "sormais", "qui", "donc", "aujourd", "hui", "devinerait", "avec", "assez",
    "certitude", "pour", "figurer", "comme", "tre", "annonciateur", "cette", "formidable", "logique", "terreurs",
    "proph", "obscurcissement", "une", "clipse", "soleil", "comme", "jamais", "produisit", "monde", "vient", "que",
    "nous", "autres", "nous", "envisagions", "mont", "cet", "obscurcissement", "sans", "tre", "vraiment", "affect",
    "surtout", "sans", "souci", "crainte", "pour", "nous", "mes", "subirions", "nous", "trop", "fortement", "peut",
    "tre", "effet", "des", "cons", "quences", "imm", "diates", "nement", "cons", "quences", "imm", "diates", "qui",
    "pour", "nous", "autres", "sont", "contrairement", "que", "pourrait", "peut", "tre", "attendre", "nullement",
    "affligeantes", "assombrissantes", "mais", "bien", "plut", "comme", "une", "lumi", "une", "licit", "soulagement",
    "gaiement", "confort", "une", "aurore", "une", "nouvelle", "sorte", "qui", "crit", "que", "difficilement", "effet",
    "nous", "autres", "philosophes", "nous", "autres", "esprits", "libres", "nouvelle", "que", "vieux", "dieu", "est",
    "mort", "nous", "nous", "sentons", "comme", "touch", "par", "les", "rayons", "une", "nouvelle", "aurore", "notre",
    "coeur", "cette", "nouvelle", "borde", "reconnaissance", "tonnement", "pressentiment", "attente", "voici",
    "horizon", "nouveau", "gag", "encore", "soit", "point", "clair", "voici", "nos", "vaisseaux", "libres", "reprendre",
    "leur", "course", "reprendre", "leur", "course", "tout", "risque"
  ]
}
