module.exports = {
  platon: [
    "platon", "publique", "premidition", "[socrate]", "bien", "mis", "avant", "dis", "par",
    "lequel", "oligarchie", "etait", "etablie", "bien", "richesse", "est", "pas", "[adimante]oui", "est",
    "sir", "insatiable", "richesse", "indiff", "rence", "gard", "tout", "reste", "induite", "par", "souci", "gagner",
    "argent", "qui", "ont", "conduite", "perte", "est", "vrai", "dit", "bien", "que", "mocratie", "finit", "comme", "bien",
    "est", "pas", "sir", "insatiable", "son", "gard", "qui", "truit", "mais", "dis", "moi", "elle", "finit", "ainsi",
    "libert", "pondis", "cela", "effet", "probablement", "dans", "une", "cit", "gouverner", "democratiquement", "entendrais",
    "que", "est", "plus", "beau", "que", "pour", "cette", "raison", "est", "seulement", "dans", "une", "telle", "cite",
    "convient", "habite", "quiconque", "est", "par", "nature", "libre", "entend", "effet", "dit", "mot", "tous", "bouts",
    "champs", "bien", "dis", "comme", "allais", "dire", "instant", "sir", "insatiable", "elle", "indiff", "rence", "gard",
    "tout", "reste", "est", "cela", "qui", "fait", "changer", "gime", "pare", "avoir", "besoin", "tyrannie", "comment", "dit",
    "quand", "semble", "une", "cit", "mocratique", "assoiff", "libert", "malheur", "tre", "dirig", "par", "mauvais", "chansons",
    "elle", "enivre", "plus", "que", "mesure", "elle", "tat", "pur", "alors", "ses", "dirigeants", "refusent", "filer", "doux",
    "lui", "laisser", "une", "totale", "libert", "elle", "tie", "ceux", "elle", "tient", "pour", "responsables", "comme", "des",
    "meurtriers", "des", "tenants", "oligarchie", "ils", "agissent", "effet", "dit", "ainsi", "ceux", "repris", "qui", "agissent",
    "aux", "dirigeants", "elle", "les", "couvre", "boue", "les", "accusant", "livrer", "eux", "esclavage", "tre", "des", "moins",
    "que", "rien", "alors", "que", "les", "dirigeants", "qui", "laissent", "diriger", "les", "dirig", "qui", "dirigent", "aussi",
    "bien", "dans", "les", "affaires", "priv", "que", "publiques", "elle", "les", "loue", "les", "honore", "est", "pas", "alors",
    "vitable", "que", "dans", "une", "telle", "cit", "soif", "libert", "vienne", "tous", "comment", "serait", "autrement", "elle",
    "insinue", "dis", "mon", "cher", "jusqu", "plus", "profond", "des", "maisons", "fin", "compte", "ait", "jusqu", "aux",
    "animaux", "qui", "anarchie", "veloppe", "que", "veux", "dire", "demanda", "que", "pondis", "habitue", "devoir", "traiter",
    "son", "fils", "gal", "gal", "craindre", "ses", "enfants", "fils", "gale", "son", "plus", "honte", "rien", "craint", "plus",
    "ses", "parents", "parce", "veut", "tre", "libre", "que", "gale", "citoyen", "citoyen", "que", "chose", "pour", "tranger",
    "est", "bien", "qui", "passe", "dit", "tout", "cela", "dis", "ajoutent", "encore", "ces", "petits", "inconv", "nients",
    "professeur", "dans", "tel", "cas", "craint", "ses", "ves", "les", "flatte", "les", "ves", "ont", "cure", "leurs",
    "professeurs", "pas", "plus", "que", "tous", "ceux", "qui", "occupent", "eux", "pour", "tout", "dire", "les", "jeunes",
    "imitent", "les", "anciens", "opposent", "violemment", "eux", "paroles", "actes", "tandis", "que", "les", "anciens",
    "abaissant", "niveau", "des", "jeunes", "gavent", "bouffoneries", "plaisanteries", "imitant", "les", "jeunes", "pour",
    "pas", "para", "tre", "sagr", "ables", "despotiques", "est", "tout", "fait", "dit", "mais", "fait", "dis", "comble", "mon",
    "cher", "exc", "libert", "tel", "appara", "dans", "une", "telle", "cit", "est", "quand", "ceux", "celles", "qui", "ont",
    "achet", "sont", "rien", "moins", "libres", "que", "ceux", "qui", "les", "ont", "achet", "dans", "les", "relations", "des",
    "hommes", "avec", "les", "femmes", "des", "femmes", "avec", "les", "hommes", "point", "arrivent", "galit", "des", "droits",
    "libert", "nous", "tions", "quasiment", "rien", "dire", "pourquoi", "pas", "pour", "citer", "eschyle", "dit", "dire", "qui",
    "nous", "est", "venu", "bouche", "instant", "bien", "repris", "est", "ainsi", "que", "parle", "quel", "point", "les", "animaux",
    "qui", "sont", "service", "homme", "sont", "beaucoup", "plus", "libres", "dans", "une", "telle", "cit", "ailleurs", "est",
    "incroyable", "pour", "qui", "pas", "exp", "rience", "car", "sans", "mentir", "les", "chiennes", "comme", "dit", "proverbe",
    "deviennent", "tous", "points", "semblables", "leur", "tresses", "les", "chevaux", "les", "nes", "habitu", "aller", "tout",
    "librement", "rement", "heurtent", "tout", "instant", "dans", "rue", "les", "passants", "qui", "cartent", "pas", "tout",
    "devient", "ainsi", "gav", "libert", "est", "dit", "mon", "propre", "que", "racontes", "car", "subis", "bien", "souvent",
    "telles", "saventures", "quand", "vais", "campagne", "sultat", "dis", "tous", "ces", "abus", "accumul", "con", "ois", "est",
    "ils", "rendent", "des", "citoyens", "licate", "approche", "moindre", "apparence", "servitude", "ils", "irritent", "peuvent",
    "supporter", "sais", "bien", "bout", "compte", "ils", "ont", "plus", "cure", "des", "lois", "crites", "non", "crites", "afin",
    "avoir", "jamais", "nulle", "part", "supporter", "tre", "combien", "dit", "sais", "bien", "dis", "mon", "cher", "tel", "est",
    "beau", "vigoureux", "commencement", "duquel", "tyrannie", "semble", "voici", "des", "hommes", "dans", "une", "habitation",
    "souterraine", "forme", "grotte", "qui", "son", "entr", "longueur", "ouvrant", "lumi", "jour", "ensemble", "grotte", "ils",
    "sont", "depuis", "leur", "enfance", "les", "jambes", "nuque", "pris", "dans", "des", "liens", "qui", "les", "obligent", "rester",
    "sur", "place", "regarder", "que", "vers", "avant", "incapables", "ils", "sont", "cause", "lien", "tourner", "leur",
    "parvient", "lumi", "feu", "qui", "haut", "loin", "derri", "eux", "entre", "feu", "les", "hommes", "encha", "une", "route",
    "dans", "hauteur", "long", "laquelle", "voici", "muret", "lev", "que", "les", "monstrateurs", "marionnettes", "disposent",
    "cloisons", "qui", "les", "parent", "des", "gens", "est", "par", "dessus", "ils", "montrent", "leurs", "merveilles",
    "vois", "aussi", "long", "muret", "des", "hommes", "qui", "portent", "des", "objets", "fabriqu", "toute", "sorte", "qui",
    "passent", "muret", "des", "statues", "hommes", "autres", "tres", "vivants", "onn", "pierre", "bois", "toutes", "mati",
    "res", "parmi", "ces", "porteurs", "comme", "est", "normal", "les", "uns", "parlent", "les", "autres", "taisent", "est",
    "une", "image", "trange", "que", "cris", "dit", "tranges", "prisonniers", "semblables", "nous", "dis", "pour", "commencer",
    "effet", "crois", "que", "tels", "hommes", "auraient", "voir", "quoi", "que", "soit", "autre", "eux", "mes", "les", "uns",
    "des", "autres", "que", "les", "ombres", "qui", "sous", "effet", "feu", "projettent", "sur", "paroi", "grotte", "face",
    "eux", "examine", "alors", "dis", "qui", "passerait", "les", "tachait", "leurs", "liens", "les", "rissait", "leur",
    "garement", "cas", "naturelle", "les", "choses", "passeraient", "peu", "comme", "suit", "chaque", "fois", "que",
    "eux", "serait", "tach", "serait", "contraint", "lever", "imm", "diatement", "retourner", "marcher", "regarder",
    "lumi", "chacun", "ces", "gestes", "souffrirait", "blouissement", "rendrait", "incapable", "distinguer", "les",
    "choses", "dont", "tout", "heure", "voyait", "les", "ombres", "que", "crois", "pondrait", "lui", "disait", "que",
    "tout", "heure", "voyait", "que", "des", "sottises", "tandis", "sent", "trouve", "peu", "plus", "qui", "est",
    "ellement", "est", "tourn", "vers", "qui", "est", "plus", "voit", "plus", "correctement", "surtout", "lui",
    "montrant", "chacune", "des", "choses", "qui", "passent", "lui", "demandait", "elle", "est", "contraignant",
    "pondre", "crois", "pas", "serait", "perdu", "consid", "rerait", "que", "voyait", "tout", "heure", "tait", "plus",
    "vrai", "que", "lui", "montre", "sent", "plus", "contraignait", "aussi", "tourner", "les", "yeux", "vers", "lumi",
    "elle", "aurait", "pas", "mal", "aux", "yeux", "fuirait", "pas", "pour", "retourner", "vers", "les", "choses", "est",
    "capable", "distinguer", "consid", "rant", "ces", "derni", "res", "comme", "ellement", "plus", "nettes", "que",
    "celles", "lui", "montre", "arrachait", "par", "force", "dis", "faisant", "monter", "par", "pente", "rocailleuse",
    "raide", "chait", "pas", "avant", "avoir", "tir", "dehors", "jusqu", "lumi", "soleil", "souffrirait", "pas",
    "indignerait", "pas", "tre", "tra", "sorte", "lorsqu", "arriverait", "lumi", "les", "yeux", "inond", "clat",
    "jour", "serait", "capable", "voir", "une", "seule", "des", "choses", "sent", "lui", "dirait", "tre", "vraies"
  ]
}
